SELECT * FROM advaita.worker;
SELECT WORKER_ID FROM worker;
SELECT WORKER_ID, FIRST_NAME FROM worker WHERE WORKER_ID='101'
SELECT WORKER_ID, FIRST_NAME FROM worker WHERE DEPARTMENT='IT' ORDER BY WORKER_ID;
SELECT WORKER_ID, FIRST_NAME FROM worker WHERE DEPARTMENT='IT' ORDER BY WORKER_ID ASC;
SELECT FIRST_NAME, SALARY FROM worker WHERE SALARY >10000 GROUP BY FIRST_NAME,SALARY ORDER BY FIRST_NAME
SELECT COUNT(SALARY),SALARY FROM worker WHERE SALARY <60000 GROUP BY SALARY ORDER BY SALARY
SELECT COUNT(WORKER_ID), FIRST_NAME FROM worker GROUP BY  SALARY
SELECT SUM(SALARY)FROM worker WHERE  SALARY<20000
SELECT AVG(SALARY)FROM worker;
SELECT *FROM student_test
SELECT *FROM advaita.student_test
SELECT FIRST_NAME, student_id FROM student_test WHERE MARKS>40
DROP student;
SELECT * FROM sys.objects WHERE Type='u'
SELECT *FROM Sys.objects WHERE TYPE='PK'
SELECT *FROM Sys.objects WHERE TYPE='uq'
SELECT *FROM Sys.objects WHERE TYPE='f'
SELECT * FROM Sys.Objects WHERE Type='tr'
SELECT * FROM Sys.Objects WHERE Type='it'
SELECT * FROM Sys.Objects WHERE Type='p'
SELECT DISTINCT WORKER_ID FROM worker
SELECT * From worker WHERE FIRST_NAME LIKE 'sneha'

SELECT WORKER_ID FROM worker WHERE
SALARY BETWEEN ‘30000’ AND ‘60000’

SELECT WORKER_ID FROM worker 
UNION SELECT SALARY FROM worker

SELECT worker_id AS cus_id FROM worker

SELECT FIRST_NAME FROM worker
WHERE WORKER_ID = ALL
(SELECT WORKER_ID FROM worker
WHERE SALARY > 30000)
	
CREATE DATABASE AllSales

CREATE TABLE Customers(
ID varchar(80),
Name varchar(80),
Phone varchar(20)
);

ALTER TABLE Customers ADD Birthday varchar(80)
	
DROP TABLE Customers
CREATE TABLE Customers (
ID int NOT NULL,
Name varchar(80) NOT NULL,
PRIMARY KEY (ID)
);
SELECT * FROM Customers

SELECT Name, Birthday, Phone, 
Address, Zip FROM Customers

SELECT Name FROM Customers WHERE EXISTS 
(SELECT Item FROM Orders 
WHERE Customers.ID = Orders.ID AND Price < 50)

SELECT CONVERT(int, 27.64)